"""empty message

Revision ID: 05c34544e59d
Revises: 3cf3a8295a1f
Create Date: 2023-11-29 23:34:18.901140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05c34544e59d"
down_revision = "3cf3a8295a1f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
