"""empty message

Revision ID: 217ccb05bc33
Revises: d25009506047
Create Date: 2023-04-14 01:48:40.064385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "217ccb05bc33"
down_revision = "d25009506047"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
