"""empty message

Revision ID: 24359f8ae3fd
Revises: baaf8adc6f7b
Create Date: 2023-04-18 14:30:03.094578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "24359f8ae3fd"
down_revision = "baaf8adc6f7b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
