"""empty message

Revision ID: 2aefd717184f
Revises: ac9688fb53fb
Create Date: 2023-12-01 18:33:29.493840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2aefd717184f"
down_revision = "ac9688fb53fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
