"""empty message

Revision ID: 35016fbe81d6
Revises: ef14dc6e86e2
Create Date: 2023-04-27 23:11:11.594809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35016fbe81d6"
down_revision = "ef14dc6e86e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("reviews_reviewer_id_key", "reviews", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("reviews_reviewer_id_key", "reviews", ["reviewer_id"])
    # ### end Alembic commands ###
