"""empty message

Revision ID: 352e48beae40
Revises: a563abd02401
Create Date: 2023-05-28 22:28:23.129160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "352e48beae40"
down_revision = "a563abd02401"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("listings", "bids_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings",
        sa.Column("bids_count", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
