"""empty message

Revision ID: 3cf3a8295a1f
Revises: 731cb71ba73c
Create Date: 2023-11-29 23:09:19.874884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3cf3a8295a1f"
down_revision = "731cb71ba73c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "listings",
        sa.Column("highest_bid", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column("listings", sa.Column("bids_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("listings", "bids_count")
    op.drop_column("listings", "highest_bid")
    # ### end Alembic commands ###
