"""empty message

Revision ID: 4f0b00c5d721
Revises: 80441d03e7bc
Create Date: 2023-04-07 21:23:21.799450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4f0b00c5d721"
down_revision = "80441d03e7bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
