"""empty message

Revision ID: 539952033c53
Revises: fe55c7bdb165
Create Date: 2023-05-13 23:36:31.386049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "539952033c53"
down_revision = "fe55c7bdb165"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("terms_agreement", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "terms_agreement")
    # ### end Alembic commands ###
