"""empty message

Revision ID: 65bae104092c
Revises: df170fd1e518
Create Date: 2023-04-10 01:25:44.374322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "65bae104092c"
down_revision = "df170fd1e518"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
