"""empty message

Revision ID: 731cb71ba73c
Revises: 27c4650d76d4
Create Date: 2023-11-29 22:54:23.336558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "731cb71ba73c"
down_revision = "27c4650d76d4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
