"""empty message

Revision ID: 80441d03e7bc
Revises: 3faf5ea12962
Create Date: 2023-04-07 21:22:35.358701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80441d03e7bc"
down_revision = "3faf5ea12962"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
