"""empty message

Revision ID: 9118a154eee6
Revises: aa08fb20859d
Create Date: 2023-04-27 03:56:31.729372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9118a154eee6"
down_revision = "aa08fb20859d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sitedetails",
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.Column("email", sa.String(length=300), nullable=True),
        sa.Column("phone", sa.String(length=300), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("fb", sa.String(length=300), nullable=True),
        sa.Column("tw", sa.String(length=300), nullable=True),
        sa.Column("wh", sa.String(length=300), nullable=True),
        sa.Column("ig", sa.String(length=300), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "suscribers",
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("exported", sa.Boolean(), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "reviews",
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column("show", sa.Boolean(), nullable=True),
        sa.Column("text", sa.String(length=100), nullable=True),
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pkid"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("reviewer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reviews")
    op.drop_table("suscribers")
    op.drop_table("sitedetails")
    # ### end Alembic commands ###
