"""empty message

Revision ID: aa08fb20859d
Revises: d6774d404b1d
Create Date: 2023-04-27 03:55:52.960759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aa08fb20859d"
down_revision = "d6774d404b1d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
