"""empty message

Revision ID: ac9688fb53fb
Revises: c2a24dc685f6
Create Date: 2023-12-01 18:15:19.037581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac9688fb53fb"
down_revision = "c2a24dc685f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
