"""empty message

Revision ID: baaf8adc6f7b
Revises: 
Create Date: 2023-04-16 00:17:58.138263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "baaf8adc6f7b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tz_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("tz_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
