"""empty message

Revision ID: bfe92a2f2879
Revises: 2aefd717184f
Create Date: 2023-12-01 22:24:08.558542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bfe92a2f2879"
down_revision = "2aefd717184f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
