"""empty message

Revision ID: c2a24dc685f6
Revises: 05c34544e59d
Create Date: 2023-11-29 23:53:16.688467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2a24dc685f6"
down_revision = "05c34544e59d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
