"""empty message

Revision ID: d25009506047
Revises: d9a84ec116a4
Create Date: 2023-04-14 01:15:34.011331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d25009506047"
down_revision = "d9a84ec116a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
